# Generated by Django 3.2.25 on 2024-10-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241030_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
