# Generated by Django 3.2.25 on 2024-10-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20241029_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, to='core.Review'),
        ),
    ]
